doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true

        mappings:
            Note:
                type: annotation
                dir: '%kernel.project_dir%/src/Note/Entity'
                alias: Note
                prefix: App\Note\Entity
                is_bundle: false

            User:
                type: annotation
                dir: '%kernel.project_dir%/src/User/Entity'
                alias: User
                prefix: App\User\Entity
                is_bundle: false
