fos_rest:
    body_converter: true
    zone:
        - {path: ^/api(?!/doc$)}
    view:
        view_response_listener: true
    exception:
        flatten_exception_format: rfc7807
        serializer_error_renderer: true
        messages:
            App\User\Exception\AuthenticationFailedException: true
    body_listener: true
    format_listener:
        rules:
            - {path: ^/api(?!/doc$), priorities: json, fallback_format: json}
