nelmio_api_doc:
    documentation:
        info:
            title: Notes
            description: A React + Symfony sample application for managing one's notes.
            version: 0.0.1
    areas:
        path_patterns:
            - ^/api(?!/doc$)
