nelmio_api_doc:
    documentation:
        info:
            title: Notes
            description: A React + Symfony sample application for managing one's notes.
            version: 0.0.1
            license: {name: MIT}

        paths:
            /api/user/login:
                post:
                    summary: Login
                    description: 'Logs in a user given its credentials.'
                    tags: [User]
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username: {type: string}
                                        password:
                                            type: string
                                            format: password

    areas:
        path_patterns:
            - ^/api(?!/doc$)
