frontend:
    resource: ../../src/Frontend/Controller
    type: annotation
    prefix: /
    name_prefix: app_frontend_

note:
    resource: ../../src/Note/Controller
    type: annotation
    prefix: /api/note
    name_prefix: app_note_

user:
    resource: ../../src/User/Controller
    type: annotation
    prefix: /api/user
    name_prefix: app_user_
